[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "app/static/fonts/SpaceGrotesk-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "Poppins"
url = "app/static/fonts/Poppins-SemiBold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "Poppins"
url = "app/static/fonts/Poppins-SemiBoldItalic.ttf"
style = "italic"
weight = 700

[[theme.fontFaces]]
family = "Poppins"
url = "app/static/fonts/Poppins-LightItalic.ttf"
style = "italic"
weight = 400

[[theme.fontFaces]]
family = "Poppins"
url = "app/static/fonts/Poppins-Light.ttf"
style = "normal"
weight = 400

[theme]
primaryColor = "#3199c6"
backgroundColor = "#fdfdf8"
secondaryBackgroundColor = "#ecebe3"
textColor = "#0A0A0A"
linkColor = "#3199c6"
borderColor = "#ecebe3"
showWidgetBorder = true
baseRadius = "7px"
# buttonRadius = "full"
font = "Poppins"
headingFontWeights = 700
headingFontSizes = ["3rem", "2rem"]
# codeFont = "SpaceMono"
codeFontSize = ".75rem"
codeBackgroundColor = "#ecebe4"
showSidebarBorder = true
chartCategoricalColors = ["#0ea5e9", "#059669", "#fbbf24"]

[theme.sidebar]
backgroundColor = "#f0f0ec"
secondaryBackgroundColor = "#ecebe3"
headingFontSizes = ["1.6rem", "1.4rem", "1.2rem"]
dataframeHeaderBackgroundColor = "#e4e4e0"